const CONFIG = {
  LEAGUES: [
    { id: 'PL', name: 'Premier League', country: 'England', color: '#37003c' },
    { id: 'PD', name: 'La Liga', country: 'Spain', color: '#e0001b' },
    { id: 'SA', name: 'Serie A', country: 'Italy', color: '#0066cc' },
    { id: 'BL1', name: 'Bundesliga', country: 'Germany', color: '#cc0000' },
    { id: 'FL1', name: 'Ligue 1', country: 'France', color: '#003366' },
    { id: 'DED', name: 'Eredivisie', country: 'Netherlands', color: '#ff6600' },
    { id: 'BSA', name: 'Brasileirão Série A', country: 'Brazil', color: '#009c3b' },
    { id: 'PPL', name: 'Primeira Liga', country: 'Portugal', color: '#006847' },
    { id: 'ELC', name: 'Championship', country: 'England', color: '#6b3fa0' },
  ],
  CUPS: [
    { id: 'CL', name: 'UEFA Champions League', country: 'Europe', color: '#003399' },
    { id: 'EC', name: 'European Championship', country: 'Europe', color: '#1a47b8' },
    { id: 'WC', name: 'World Cup', country: 'World', color: '#f7d002' },
  ],
  ALL: [
    { id: 'PL', name: 'Premier League', country: 'England', color: '#37003c', type: 'league' },
    { id: 'PD', name: 'La Liga', country: 'Spain', color: '#e0001b', type: 'league' },
    { id: 'SA', name: 'Serie A', country: 'Italy', color: '#0066cc', type: 'league' },
    { id: 'BL1', name: 'Bundesliga', country: 'Germany', color: '#cc0000', type: 'league' },
    { id: 'FL1', name: 'Ligue 1', country: 'France', color: '#003366', type: 'league' },
    { id: 'DED', name: 'Eredivisie', country: 'Netherlands', color: '#ff6600', type: 'league' },
    { id: 'BSA', name: 'Brasileirão Série A', country: 'Brazil', color: '#009c3b', type: 'league' },
    { id: 'PPL', name: 'Primeira Liga', country: 'Portugal', color: '#006847', type: 'league' },
    { id: 'ELC', name: 'Championship', country: 'England', color: '#6b3fa0', type: 'league' },
    { id: 'CL', name: 'UEFA Champions League', country: 'Europe', color: '#003399', type: 'cup' },
    { id: 'EC', name: 'European Championship', country: 'Europe', color: '#1a47b8', type: 'cup' },
    { id: 'WC', name: 'World Cup', country: 'World', color: '#f7d002', type: 'cup' },
  ],
  SPORTS: [
    { id: 'football', name: 'Football', icon: '⚽', color: '#00e676' },
    { id: 'basketball', name: 'Basketball', icon: '🏀', color: '#ff6b35' },
    { id: 'fight', name: 'Boxing & UFC', icon: '🥊', color: '#ff1744' },
    { id: 'tennis', name: 'Tennis', icon: '🎾', color: '#7c4dff' },
    { id: 'americanfootball', name: 'American Football', icon: '🏈', color: '#ff3d00' },
    { id: 'hockey', name: 'Hockey', icon: '🏒', color: '#00bcd4' },
    { id: 'baseball', name: 'Baseball', icon: '⚾', color: '#ffab00' },
    { id: 'motorsport', name: 'Motor Sports', icon: '🏎️', color: '#e91e63' },
    { id: 'rugby', name: 'Rugby', icon: '🏉', color: '#4caf50' },
    { id: 'golf', name: 'Golf', icon: '⛳', color: '#2e7d32' },
    { id: 'cricket', name: 'Cricket', icon: '🏏', color: '#0097a7' },
    { id: 'darts', name: 'Darts', icon: '🎯', color: '#f44336' },
    { id: 'billiards', name: 'Billiards', icon: '🎱', color: '#9e9e9e' },
    { id: 'afl', name: 'AFL', icon: '🏉', color: '#1565c0' },
  ],
  TV_COUNTRIES: [
    { id: 'int', name: 'International', flag: '🌍' },
    { id: 'us', name: 'United States', flag: '🇺🇸' },
    { id: 'uk', name: 'United Kingdom', flag: '🇬🇧' },
    { id: 'fr', name: 'France', flag: '🇫🇷' },
    { id: 'de', name: 'Germany', flag: '🇩🇪' },
    { id: 'qa', name: 'Qatar', flag: '🇶🇦' },
    { id: 'ru', name: 'Russia', flag: '🇷🇺' },
    { id: 'jp', name: 'Japan', flag: '🇯🇵' },
    { id: 'cn', name: 'China', flag: '🇨🇳' },
    { id: 'tr', name: 'Turkey', flag: '🇹🇷' },
    { id: 'au', name: 'Australia', flag: '🇦🇺' },
    { id: 'ca', name: 'Canada', flag: '🇨🇦' },
  ],
  TV_CHANNELS: [
    { id: 'france24-en', name: 'France 24 English', country: 'int', flag: '🌍', type: 'news', embed: 'https://www.france24.fr/en/live-embed' },
    { id: 'france24-fr', name: 'France 24 Français', country: 'int', flag: '🌍', type: 'news', embed: 'https://www.france24.fr/fr/live-embed' },
    { id: 'aljazeera', name: 'Al Jazeera English', country: 'int', flag: '🌍', type: 'news', embed: 'https://www.aljazeera.com/live' },
    { id: 'dw-news', name: 'DW News', country: 'int', flag: '🌍', type: 'news', embed: 'https://www.dw.com/en/live-tv' },
    { id: 'euronews', name: 'Euronews', country: 'int', flag: '🌍', type: 'news', embed: 'https://www.euronews.com/live' },
    { id: 'trtworld', name: 'TRT World', country: 'int', flag: '🌍', type: 'news', embed: 'https://www.trtworld.com/live' },
    { id: 'nhkworld', name: 'NHK World Japan', country: 'int', flag: '🌍', type: 'news', embed: 'https://www3.nhk.or.jp/nhkworld/en/live/embed/' },
    { id: 'cgtn', name: 'CGTN', country: 'int', flag: '🌍', type: 'news', embed: 'https://www.cgtn.com/embed/' },
    { id: 'rt-news', name: 'RT News', country: 'int', flag: '🌍', type: 'news', embed: 'https://www.rt.com/on-air/' },
    { id: 'abc-news', name: 'ABC News Live', country: 'us', flag: '🇺🇸', type: 'news', embed: 'https://abcnews.go.com/live' },
    { id: 'cbs-news', name: 'CBS News', country: 'us', flag: '🇺🇸', type: 'news', embed: 'https://www.cbsnews.com/live/' },
    { id: 'nbc-news', name: 'NBC News Now', country: 'us', flag: '🇺🇸', type: 'news', embed: 'https://www.nbcnews.com/live' },
    { id: 'bloomberg', name: 'Bloomberg TV', country: 'us', flag: '🇺🇸', type: 'business', embed: 'https://www.bloomberg.com/live/' },
    { id: 'sky-news', name: 'Sky News', country: 'uk', flag: '🇬🇧', type: 'news', embed: 'https://www.youtube.com/embed/live_stream?channel=UCO3sN8f5jVvM-amYFjA8z8w' },
    { id: 'bfmtv', name: 'BFM TV', country: 'fr', flag: '🇫🇷', type: 'news', embed: 'https://www.bfmtv.com/mediaplayer/live/' },
    { id: 'dw-de', name: 'DW Deutsch', country: 'de', flag: '🇩🇪', type: 'news', embed: 'https://www.dw.com/de/live-tv' },
    { id: 'ntv', name: 'n-tv', country: 'de', flag: '🇩🇪', type: 'news', embed: 'https://www.n-tv.de/live/' },
    { id: 'rt-ru', name: 'RT на русском', country: 'ru', flag: '🇷🇺', type: 'news', embed: 'https://www.rt.com/on-air/' },
    { id: 'nhk-g', name: 'NHK General TV', country: 'jp', flag: '🇯🇵', type: 'general', embed: 'https://www3.nhk.or.jp/nhkworld/en/live/embed/' },
    { id: 'cctv4', name: 'CCTV-4', country: 'cn', flag: '🇨🇳', type: 'news', embed: 'https://tv.cctv.com/live/cctv4/' },
    { id: 'trt-haber', name: 'TRT Haber', country: 'tr', flag: '🇹🇷', type: 'news', embed: 'https://www.trthaber.com/canli-yayin/' },
    { id: 'abc-au', name: 'ABC Australia', country: 'au', flag: '🇦🇺', type: 'news', embed: 'https://www.abc.net.au/news/live/' },
    { id: 'cbc-news', name: 'CBC News', country: 'ca', flag: '🇨🇦', type: 'news', embed: 'https://www.cbc.ca/live/news' },
  ],
  TEAM_LEAGUE_MAP: {
    'Arsenal': 'PL', 'Man City': 'PL', 'Man United': 'PL', 'Liverpool': 'PL',
    'Chelsea': 'PL', 'Tottenham': 'PL', 'Newcastle': 'PL', 'Aston Villa': 'PL',
    'Brighton': 'PL', 'Brentford': 'PL', 'Fulham': 'PL', 'Everton': 'PL',
    'West Ham': 'PL', 'Crystal Palace': 'PL', 'Wolves': 'PL', 'Nottingham': 'PL',
    'Leicester': 'PL', 'Leeds': 'PL', 'Southampton': 'PL',
    'Barcelona': 'PD', 'Real Madrid': 'PD', 'Atletico Madrid': 'PD', 'Sevilla': 'PD',
    'Valencia': 'PD', 'Real Betis': 'PD', 'Villarreal': 'PD', 'Athletic Club': 'PD',
    'Real Sociedad': 'PD',
    'Juventus': 'SA', 'Milan': 'SA', 'Inter': 'SA', 'Roma': 'SA', 'Napoli': 'SA',
    'Lazio': 'SA', 'Atalanta': 'SA', 'Fiorentina': 'SA',
    'Bayern': 'BL1', 'Dortmund': 'BL1', 'Leverkusen': 'BL1', 'Leipzig': 'BL1',
    'Stuttgart': 'BL1', 'Wolfsburg': 'BL1', 'Gladbach': 'BL1',
    'PSG': 'FL1', 'Marseille': 'FL1', 'Lyon': 'FL1', 'Monaco': 'FL1', 'Lille': 'FL1',
    'Nice': 'FL1', 'Lens': 'FL1',
  }
};
